### ISSUE TITLE
Contract transaction dry-run should happen every time an input is changed

### ISSUE THREAD

**Issue by cmichi** [paritytech/contracts-ui#442] opened 2023-03-20 05:31 UTC
It could be that this is already fixed for Contracts UI, I'm not sure.

Please execute the reproduction steps from https://github.com/polkadot-js/apps/issues/6603 to find out if the error is also happening for Contracts UI.

**Comment by statictype** [comment] 2023-03-20 14:51
Unable to reproduce, the code is rejected even on `WeightV1` testnets

I can confirm that the dry run is performed when changing the caller account or any other inputs in the instantiation / interaction forms. 

There are some cases where this doesn't work. Will close this in favor of https://github.com/paritytech/contracts-ui/issues/445

**Closed by statictype** 2023-03-20 14:51 UTC
Labels: good first issue
