### ISSUE TITLE
Unnecessary repeating of upload a `CodeRejected` contract over and over again

### ISSUE THREAD

**Issue by agryaznov** [paritytech/contracts-ui#377] opened 2022-11-25 20:05 UTC
**Describe the bug**
Seems that Contracts-UI keeps trying to upload the same contract which was rejected with `CodeRejected` again and again, until we leave the `/instantiate` view.

**To Reproduce**

1. Launch a local contracts-node with `substrate-contracts-node -linfo,runtime::contracts=debug`
1. Go to https://weightv1--contracts-ui.netlify.app/instantiate
2. Upload some contract which leads to `CodeRejected` e.g the `greeter.contract` from [this issue](https://github.com/paritytech/cargo-contract/issues/832) description.
3. See `CodeRejected` error appeared in the Contract-UI, which is right. 
4. Open to the node's debug log and see the error continues to be raised again and again and again untill you move away from the instantiate view of the Contracts-UI or just close the browser tab.
![Screenshot from 2022-11-22 16-06-49](https://user-images.githubusercontent.com/3878903/204049944-061a917f-53b8-4ecb-8e12-338ca15012d4.png)

**Expected behavior**
The error should have been raised only once on the node side.

**Additional context**
With the same steps repeated in the PolkadotJS, the node raises the error just once, as expected.

**Comment by athei** [comment] 2022-11-25 20:14
> 1. Launch a local contracts-node with `substrate-contracts-node -linfo,runtime::contracts=debug`

Those logging parameters are the defaults since a few versions ago btw.

**Comment by statictype** [comment] 2022-12-18 20:49
Thanks for reporting this @agryaznov 
I tried to reproduce it and it only happens with the old Contracts UI and nodes and only in the case of a `CodeRejected` error so i don't think it's really worth fixing since it such an edge case. Will close this for now but if you think it's important, please reopen!

**Closed by statictype** 2022-12-18 20:49 UTC
